#!/bin/bash
if [ "$EUID" -ne 0 ]; then
  echo "Please run this script as root or using sudo."
  exit 1
fi

custom_script_name="start"

custom_remove_name="remove"

custom_script_source="script.sh"

custom_remove_source="uninstall.sh"

install_dir="/usr/local/bin"

cp "$custom_script_source" "$install_dir/$custom_script_name"
cp "$custom_remove_source" "$install_dir/$custom_remove_name"
chmod +x "$install_dir/$custom_script_name"
chmod +x "$install_dir/$custom_remove_name"
sleep 5
echo "Installing... 20%"
sleep 3
echo "Installing... 40%"
sleep 3
echo "Installing... 60%"
sleep 3
echo "Setting up 'start'... 80%"
sleep 2
echo "Setup Completed!!! 100%"
sleep 2
echo "Script '$custom_script_name' has been installed. You can now run it from anywhere using: $custom_script_name"
sleep 3
echo "Adding 'remove'... 50%"
sleep 2
echo "Completed!!!... 100"
sleep 2
echo "Script '$custom_remove_name' has been installed. You can now run it from anywhere using: $custom_remove_name to uninstall $custom_script_name"
sleep 4
echo "Installation Script inspiration from faithfull https://github.com/faithful1ofall/"
echo "Developed by Joseph John https://github.com/Josephjbassey"
